name: gcc-build-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
permissions:
  contents: write
  
jobs:
  build:
    strategy:
      matrix:
        compiler:
        # - {
        #     name: "x86_64-8.1.0-release-posix-seh-rt_v6-rev0",
        #     url: "https://github.com/dirkarnez/cpp-tools/raw/main/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z"
        #   }
        - {
            name: "winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1",
            url: "https://github.com/brechtsanders/winlibs_mingw/releases/download/11.2.0-12.0.1-9.0.0-r1/winlibs-x86_64-posix-seh-gcc-11.2.0-mingw-w64-9.0.0-r1.zip"
          }
        # - {
        #     name: "msvc2019"
        #   }
    env:
      tagName: 'releases/gcc-14.2.0'
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'gcc-mirror/gcc'
          ref: ${{ env.tagName }}
          submodules: true
          
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: make autoconf automake libtool autogen perl

      - name: download compiler
        if: ${{  matrix.compiler.url }}
        shell: cmd
        run: |
          curl ${{ matrix.compiler.url }} -L --output compiler &&^
          7z.exe x compiler

      - name: set PATH, check mingw version, cmake generate, build and install
        shell: msys2 {0}
        run: |
          workspace=$(pwd) &&
          export PATH="$workspace/mingw64:$workspace/mingw64/bin:$workspace/msys64/usr/bin:/usr/bin" &&
          g++ --version && 
          mkdir objdir &&
          cd objdir &&
          ../gcc/configure --enable-languages=c,c++ --prefix="$(pwd)/${{ env.installationPath }}" &&
          make install && 
          ls
            
